### ISSUE TITLE
Admin 유저 조회 불가능

### ISSUE THREAD

**Issue by craftingmod** [sdbx/minda#5]
![image](https://user-images.githubusercontent.com/9389278/51505579-b8d5f480-1e2a-11e9-871a-feb880bf524b.png)

??

**Comment by sunho** [comment]
Get은 안되는 것이 정상!

**Comment by sunho** [comment]
Get이 아니였군 비몽사몽해서 잘못봄

**Comment by craftingmod** [comment]
낮잠 주무시고 천천히 하시죠

**Comment by sunho** [comment]
f0c4569
